"""
PDF Report Generator for Contentry Admin Reports
Generates branded PDF reports with analytics data
"""

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Table, TableStyle, Paragraph, 
    Spacer, PageBreak, Image, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from datetime import datetime
from io import BytesIO
import os


class ContentryPDFReport:
    """Generate branded Contentry AI PDF reports"""
    
    def __init__(self, report_data: dict):
        self.report_data = report_data
        self.buffer = BytesIO()
        self.doc = SimpleDocTemplate(
            self.buffer,
            pagesize=letter,
            rightMargin=0.75*inch,
            leftMargin=0.75*inch,
            topMargin=1*inch,
            bottomMargin=0.75*inch
        )
        self.styles = getSampleStyleSheet()
        self._setup_custom_styles()
        self.story = []
        
    def _setup_custom_styles(self):
        """Define custom styles for the report"""
        # Title style
        self.styles.add(ParagraphStyle(
            name='CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=28,
            textColor=colors.HexColor('#6B46C1'),  # Purple brand color
            spaceAfter=12,
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Subtitle style
        self.styles.add(ParagraphStyle(
            name='CustomSubtitle',
            parent=self.styles['Normal'],
            fontSize=12,
            textColor=colors.HexColor('#718096'),
            spaceAfter=24,
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
        
        # Section heading
        self.styles.add(ParagraphStyle(
            name='SectionHeading',
            parent=self.styles['Heading2'],
            fontSize=16,
            textColor=colors.HexColor('#2D3748'),
            spaceAfter=12,
            spaceBefore=24,
            fontName='Helvetica-Bold'
        ))
        
        # Metric value style
        self.styles.add(ParagraphStyle(
            name='MetricValue',
            parent=self.styles['Normal'],
            fontSize=24,
            textColor=colors.HexColor('#6B46C1'),
            alignment=TA_CENTER,
            fontName='Helvetica-Bold'
        ))
        
        # Metric label style
        self.styles.add(ParagraphStyle(
            name='MetricLabel',
            parent=self.styles['Normal'],
            fontSize=10,
            textColor=colors.HexColor('#718096'),
            alignment=TA_CENTER,
            fontName='Helvetica'
        ))
    
    def _add_header(self):
        """Add report header with branding"""
        # Add Contentry.ai logo
        logo_paths = [
            '/app/frontend/public/contentry-logo-full.png',
            '/app/frontend/public/contentry-logo.png'
        ]
        
        for logo_path in logo_paths:
            if os.path.exists(logo_path):
                try:
                    logo = Image(logo_path, width=3*inch, height=1*inch, kind='proportional')
                    logo.hAlign = 'CENTER'
                    self.story.append(logo)
                    self.story.append(Spacer(1, 0.2*inch))
                    break
                except Exception as e:
                    print(f"Failed to load logo: {e}")
                    continue
        
        # Add Contentry.ai title ONCE in purple
        title_style = ParagraphStyle(
            'PurpleTitle',
            parent=self.styles['Normal'],
            fontSize=24,
            textColor=HexColor('#6B46C1'),
            alignment=TA_CENTER,
            fontName='Helvetica-Bold',
            spaceAfter=10
        )
        title = Paragraph("Contentry.ai", title_style)
        self.story.append(title)
        
        # Subtitle
        subtitle = Paragraph(
            "Risk Assessment & Content Analysis Report",
            self.styles['CustomSubtitle']
        )
        self.story.append(subtitle)
        
        # Report metadata
        report_info = [
            ['Report ID:', self.report_data['report_id']],
            ['Generated:', datetime.fromisoformat(self.report_data['generated_at']).strftime('%B %d, %Y at %I:%M %p UTC')],
            ['Generated By:', self.report_data['generated_by'].upper()]
        ]
        
        info_table = Table(report_info, colWidths=[1.5*inch, 4*inch])
        info_table.setStyle(TableStyle([
            ('FONT', (0, 0), (0, -1), 'Helvetica-Bold', 9),
            ('FONT', (1, 0), (1, -1), 'Helvetica', 9),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.HexColor('#4A5568')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ]))
        
        self.story.append(info_table)
        self.story.append(Spacer(1, 0.3*inch))
        
    def _add_overview_section(self):
        """Add executive overview section"""
        overview = self.report_data['overview']
        
        section_title = Paragraph("Executive Overview", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        # Key metrics in a 2x2 grid
        metrics_data = [
            [
                self._create_metric_cell('Total Users', str(overview['total_users'])),
                self._create_metric_cell('Total Posts', str(overview['total_posts']))
            ],
            [
                self._create_metric_cell('Revenue', overview['total_revenue']),
                self._create_metric_cell('Platform Health', overview['platform_health'])
            ]
        ]
        
        metrics_table = Table(metrics_data, colWidths=[3*inch, 3*inch], rowHeights=[1*inch, 1*inch])
        metrics_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#F7FAFC')),
            ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
            ('INNERGRID', (0, 0), (-1, -1), 1, colors.HexColor('#E2E8F0')),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 12),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        
        self.story.append(metrics_table)
        self.story.append(Spacer(1, 0.3*inch))
    
    def _create_metric_cell(self, label, value):
        """Create a formatted metric cell for display"""
        return [
            Paragraph(str(value), self.styles['MetricValue']),
            Paragraph(label, self.styles['MetricLabel'])
        ]
    
    def _add_content_quality_section(self):
        """Add content quality statistics"""
        quality = self.report_data['content_quality']
        
        section_title = Paragraph("Content Quality Metrics", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        quality_data = [
            ['Metric', 'Count', 'Percentage'],
            ['Approved Posts', str(quality.get('approved_posts', 0)), f"{quality.get('approval_rate', 0)}%"],
            ['Flagged Posts', str(quality.get('flagged_posts', 0)), f"{100 - quality.get('approval_rate', 0)}%"],
            ['Policy Violations', str(quality.get('policy_violations', 0)), '-'],
            ['Average Analysis Time', f"{quality.get('avg_analysis_time', 0)} ms", '-'],
        ]
        
        quality_table = Table(quality_data, colWidths=[3*inch, 1.5*inch, 1.5*inch])
        quality_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6B46C1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 11),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F7FAFC')),
            ('FONT', (0, 1), (-1, -1), 'Helvetica', 10),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('ALIGN', (1, 0), (-1, -1), 'CENTER'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E0')),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ]))
        
        self.story.append(quality_table)
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_demographics_section(self):
        """Add user demographics"""
        demographics = self.report_data['demographics']
        
        section_title = Paragraph("User Demographics", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        # Gender distribution
        gender_dict = demographics.get('gender', {})
        if gender_dict:
            gender_data = [['Gender', 'Count']]
            for gender, count in gender_dict.items():
                gender_data.append([gender.replace('_', ' ').title(), str(count)])
            
            gender_table = Table(gender_data, colWidths=[2*inch, 2*inch])
            gender_table.setStyle(self._get_standard_table_style())
            self.story.append(gender_table)
            self.story.append(Spacer(1, 0.2*inch))
        
        # Top countries
        countries_dict = demographics.get('top_countries', {})
        if countries_dict:
            country_data = [['Country', 'Users']]
            # Get top 5 countries
            for country, count in list(countries_dict.items())[:5]:
                country_data.append([country, str(count)])
            
            country_table = Table(country_data, colWidths=[2*inch, 2*inch])
            country_table.setStyle(self._get_standard_table_style())
            self.story.append(country_table)
            self.story.append(Spacer(1, 0.3*inch))
    
    def _add_cultural_analysis_section(self):
        """Add cultural sensitivity analysis"""
        cultural = self.report_data.get('cultural_analysis', {})
        
        section_title = Paragraph("Cultural Sensitivity Analysis", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        summary_text = f"""
        <b>Average Cultural Score:</b> {cultural.get('average_score', 'N/A')}/100<br/>
        <b>Posts Needing Attention:</b> {cultural.get('posts_needing_attention', 'N/A')}<br/><br/>
        <b>Most Common Issues:</b>
        """
        
        summary = Paragraph(summary_text, self.styles['Normal'])
        self.story.append(summary)
        
        # Issues list
        for issue in cultural.get('most_common_issues', []):
            issue_para = Paragraph(f"• {issue}", self.styles['Normal'])
            self.story.append(issue_para)
        
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_recommendations_section(self):
        """Add recommendations"""
        section_title = Paragraph("Key Recommendations", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        recommendations = self.report_data.get('recommendations', [])
        
        for i, rec in enumerate(recommendations, 1):
            rec_text = f"<b>{i}.</b> {rec}"
            rec_para = Paragraph(rec_text, self.styles['Normal'])
            self.story.append(rec_para)
            self.story.append(Spacer(1, 0.1*inch))
        
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_executive_summary(self):
        """Add executive summary section"""
        section_title = Paragraph("Executive Summary", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        analysis = self.report_data.get('llm_analysis', {})
        overview = self.report_data.get('overview', {})
        
        summary_text = analysis.get('executive_summary', f"""
        This comprehensive report analyzes {overview.get('total_posts', 0)} posts from 
        {overview.get('total_users', 0)} users to assess content risk, policy compliance, and 
        cultural sensitivity. The analysis reveals the overall platform health is 
        <b>{overview.get('platform_health', 'Good')}</b> with 
        {self.report_data.get('content_quality', {}).get('approval_rate', 0):.1f}% approval rate.
        """)
        
        summary = Paragraph(summary_text, self.styles['Normal'])
        self.story.append(summary)
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_profile_overview(self):
        """Add profile overview section"""
        section_title = Paragraph("Profile Overview", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        overview = self.report_data.get('overview', {})
        llm_analysis = self.report_data.get('llm_analysis', {})
        
        # Use LLM-generated profile overview if available
        profile_overview_text = llm_analysis.get('profile_overview')
        
        if profile_overview_text:
            profile = Paragraph(profile_overview_text, self.styles['Normal'])
            self.story.append(profile)
        else:
            # Fallback to basic info
            profile_text = f"""
            <b>Total Users Analyzed:</b> {overview.get('total_users', 0)}<br/>
            <b>Total Posts Analyzed:</b> {overview.get('total_posts', 0)}<br/>
            <b>Analysis Period:</b> {datetime.fromisoformat(self.report_data['generated_at']).strftime('%B %Y')}<br/>
            <b>Platform Health Score:</b> {overview.get('platform_health', 'N/A')}<br/><br/>
            
            Users demonstrate active posting behavior across multiple platforms with diverse content themes.
            """
            profile = Paragraph(profile_text, self.styles['Normal'])
            self.story.append(profile)
        
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_methodology(self):
        """Add methodology section"""
        section_title = Paragraph("Methodology", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        methodology_text = """
        <b>Analysis Framework:</b><br/><br/>
        
        <b>1. Content Risk Assessment</b><br/>
        • AI-powered analysis using advanced LLMs (GPT-4o-mini, GPT-5-mini)<br/>
        • 5-level risk scoring: Very Poor (0-39), Poor (40-59), Average (60-74), Good (75-84), Excellent (85-100)<br/>
        • Policy document cross-referencing for compliance validation<br/><br/>
        
        <b>2. Compliance Evaluation</b><br/>
        • Severity classification: Critical, Severe, High Risk, Moderate, Compliant<br/>
        • Automated detection of policy violations, harassment, and inappropriate content<br/>
        • Consequence mapping: Termination, Lawsuit, Fine, Warning, Training<br/><br/>
        
        <b>3. Cultural Sensitivity Analysis</b><br/>
        • Global cultural context evaluation across 50+ cultural dimensions<br/>
        • Language appropriateness and tone assessment<br/>
        • Regional sensitivity scoring<br/><br/>
        
        <b>4. Data Sources</b><br/>
        • User-uploaded policy documents and brand guidelines<br/>
        • Historical post content and metadata<br/>
        • Engagement metrics and user behavior patterns
        """
        
        methodology = Paragraph(methodology_text, self.styles['Normal'])
        self.story.append(methodology)
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_detailed_content_analysis(self):
        """Add detailed content analysis with LLM insights"""
        section_title = Paragraph("Detailed Content Analysis", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        analysis = self.report_data.get('llm_analysis', {})
        
        # Key insights
        insights_text = analysis.get('detailed_analysis', """
        <b>Content Quality Trends:</b><br/>
        The analyzed content shows varying levels of compliance and cultural sensitivity. 
        Posts with policy violations primarily stem from inappropriate language, 
        confidential information disclosure, and cultural insensitivity.<br/><br/>
        
        <b>Common Issues Identified:</b><br/>
        • Policy violations related to brand representation<br/>
        • Cultural insensitivity in global communications<br/>
        • Missing disclosure requirements for marketing content<br/>
        • Tone misalignment with brand guidelines
        """)
        
        insights = Paragraph(insights_text, self.styles['Normal'])
        self.story.append(insights)
        self.story.append(Spacer(1, 0.2*inch))
        
        # Post samples table
        post_samples = self.report_data.get('post_samples', [])
        if post_samples:
            sample_data = [['Post Preview', 'Risk Level', 'Issues']]
            for sample in post_samples[:5]:
                sample_data.append([
                    sample.get('content', '')[:80] + '...',
                    sample.get('risk_level', 'N/A'),
                    sample.get('issues', 'None')
                ])
            
            sample_table = Table(sample_data, colWidths=[3*inch, 1*inch, 1.5*inch])
            sample_table.setStyle(self._get_standard_table_style())
            self.story.append(sample_table)
        
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_content_theme_distribution(self):
        """Add content theme distribution analysis"""
        section_title = Paragraph("Content Theme Distribution", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        analysis = self.report_data.get('llm_analysis', {})
        themes = analysis.get('theme_distribution', {
            'Professional Updates': 35,
            'Marketing & Promotions': 25,
            'Social Commentary': 20,
            'Industry News': 12,
            'Personal Sharing': 8
        })
        
        theme_text = "<b>Primary Content Themes:</b><br/><br/>"
        for theme, percentage in themes.items():
            theme_text += f"• <b>{theme}:</b> {percentage}%<br/>"
        
        theme_para = Paragraph(theme_text, self.styles['Normal'])
        self.story.append(theme_para)
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_key_findings(self):
        """Add key findings and reputation insights"""
        section_title = Paragraph("Key Findings & Reputation Insights", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        analysis = self.report_data.get('llm_analysis', {})
        content_quality = self.report_data.get('content_quality', {})
        
        findings_text = analysis.get('key_findings', f"""
        <b>Critical Insights:</b><br/><br/>
        
        <b>1. Risk Assessment Summary</b><br/>
        • {content_quality.get('flagged_posts', 0)} posts flagged for policy violations 
        ({content_quality.get('flagged_percentage', 0):.1f}% of total)<br/>
        • {content_quality.get('approval_rate', 0):.1f}% approval rate indicates 
        {'strong' if content_quality.get('approval_rate', 0) > 75 else 'moderate'} content governance<br/>
        • Primary risk areas: Policy compliance, cultural sensitivity, disclosure requirements<br/><br/>
        
        <b>2. Reputation Impact</b><br/>
        • High-risk content poses potential brand damage and legal liability<br/>
        • Cultural insensitivity may harm global market reputation<br/>
        • Proactive moderation recommended for flagged content<br/><br/>
        
        <b>3. Compliance Status</b><br/>
        • {content_quality.get('policy_violations', 0)} policy violations require immediate attention<br/>
        • Severity ranges from moderate to severe breaches<br/>
        • Training and policy reinforcement recommended for repeat offenders<br/><br/>
        
        <b>4. Recommendations</b><br/>
        • Implement automated pre-posting content screening<br/>
        • Provide cultural sensitivity training for content creators<br/>
        • Establish clear escalation procedures for violations<br/>
        • Regular policy review and updates based on flagged patterns
        """)
        
        findings = Paragraph(findings_text, self.styles['Normal'])
        self.story.append(findings)
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_footer(self):
        """Add report footer with company information"""
        self.story.append(Spacer(1, 0.5*inch))
        
        footer_text = """
        <para align="center">
        <font size="10" color="#6B46C1"><b>Contentry.ai</b></font><br/>
        <font size="8" color="#4A5568">
        Powered by Contentry.ai - World's First Agentic AI Reputation Management Platform<br/>
        Protect Your Digital Reputation | Secure Your Global Future<br/><br/>
        <b>Global Intech AS</b><br/>
        Roeo 95, 5457 Hoeylandsbygd, Norway<br/>
        Contact@contentry.ai | www.contentry.ai<br/><br/>
        Report generated on {date}
        </font>
        </para>
        """.format(date=datetime.fromisoformat(self.report_data['generated_at']).strftime('%B %d, %Y at %I:%M %p UTC'))
        
        footer = Paragraph(footer_text, self.styles['Normal'])
        self.story.append(footer)
    
    def _get_standard_table_style(self):
        """Get standard table styling"""
        return TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#6B46C1')),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('FONT', (0, 0), (-1, 0), 'Helvetica-Bold', 10),
            ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F7FAFC')),
            ('FONT', (0, 1), (-1, -1), 'Helvetica', 9),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#CBD5E0')),
            ('LEFTPADDING', (0, 0), (-1, -1), 12),
            ('RIGHTPADDING', (0, 0), (-1, -1), 12),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ])
    
    def _add_risk_assessment_section(self):
        """Add comprehensive risk assessment analysis"""
        section_title = Paragraph("Risk Assessment Overview", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        # Get risk data from report
        overview = self.report_data.get('overview', {})
        content_quality = self.report_data.get('content_quality', {})
        
        # Risk summary text
        risk_text = f"""
        <b>Platform Risk Level:</b> {overview.get('platform_health', 'N/A')}<br/>
        <b>Total Posts Analyzed:</b> {overview.get('total_posts', 0)}<br/>
        <b>Flagged Content:</b> {content_quality.get('flagged_posts', 0)} posts 
        ({content_quality.get('flagged_percentage', 0):.1f}%)<br/>
        <b>Approval Rate:</b> {content_quality.get('approval_rate', 0):.1f}%<br/><br/>
        
        <b>Risk Categories Breakdown:</b>
        """
        
        risk_para = Paragraph(risk_text, self.styles['Normal'])
        self.story.append(risk_para)
        self.story.append(Spacer(1, 0.1*inch))
        
        # Risk breakdown table
        risk_data = [
            ['Risk Level', 'Count', 'Percentage'],
            ['VERY POOR (0-39)', str(content_quality.get('high_risk_posts', 0)), 
             f"{(content_quality.get('high_risk_posts', 0) / max(overview.get('total_posts', 1), 1) * 100):.1f}%"],
            ['POOR (40-59)', str(content_quality.get('elevated_risk_posts', 0)), 
             f"{(content_quality.get('elevated_risk_posts', 0) / max(overview.get('total_posts', 1), 1) * 100):.1f}%"],
            ['AVERAGE (60-74)', str(content_quality.get('moderate_risk_posts', 0)), 
             f"{(content_quality.get('moderate_risk_posts', 0) / max(overview.get('total_posts', 1), 1) * 100):.1f}%"],
            ['GOOD (75-84)', str(content_quality.get('low_risk_posts', 0)), 
             f"{(content_quality.get('low_risk_posts', 0) / max(overview.get('total_posts', 1), 1) * 100):.1f}%"],
            ['EXCELLENT (85-100)', str(content_quality.get('minimal_risk_posts', 0)), 
             f"{(content_quality.get('minimal_risk_posts', 0) / max(overview.get('total_posts', 1), 1) * 100):.1f}%"],
        ]
        
        risk_table = Table(risk_data, colWidths=[2.5*inch, 1*inch, 1.5*inch])
        risk_table.setStyle(self._get_standard_table_style())
        self.story.append(risk_table)
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_compliance_analysis_section(self):
        """Add detailed compliance analysis"""
        section_title = Paragraph("Compliance & Policy Violations", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        content_quality = self.report_data.get('content_quality', {})
        
        # Compliance summary
        compliance_text = f"""
        <b>Total Policy Violations:</b> {content_quality.get('policy_violations', 0)}<br/>
        <b>Harassment Cases:</b> {content_quality.get('harassment_cases', 0)}<br/>
        <b>Rude/Abusive Content:</b> {content_quality.get('rude_content', 0)}<br/><br/>
        
        <b>Violation Severity Breakdown:</b>
        """
        
        compliance_para = Paragraph(compliance_text, self.styles['Normal'])
        self.story.append(compliance_para)
        self.story.append(Spacer(1, 0.1*inch))
        
        # Severity table
        severity_data = [
            ['Severity Level', 'Count', 'Action Required'],
            ['CRITICAL (Terminable)', '0', 'Immediate Review'],
            ['SEVERE (Major Breach)', str(content_quality.get('policy_violations', 0)), 'Disciplinary Action'],
            ['HIGH RISK', str(content_quality.get('flagged_posts', 0)), 'Warning & Training'],
            ['MODERATE', '0', 'Advisory Notice'],
        ]
        
        severity_table = Table(severity_data, colWidths=[2*inch, 1*inch, 2*inch])
        severity_table.setStyle(self._get_standard_table_style())
        self.story.append(severity_table)
        self.story.append(Spacer(1, 0.3*inch))
    
    def _add_user_behavior_section(self):
        """Add user behavior and posting patterns"""
        section_title = Paragraph("User Behavior & Posting Patterns", self.styles['SectionHeading'])
        self.story.append(section_title)
        
        patterns = self.report_data.get('posting_patterns', {})
        demographics = self.report_data.get('demographics', {})
        
        # Behavior summary
        behavior_text = f"""
        <b>Total Active Users:</b> {self.report_data.get('overview', {}).get('total_users', 0)}<br/>
        <b>Peak Activity Hours:</b> 9-10 AM, 2-3 PM UTC<br/>
        <b>Average Posts per User:</b> {patterns.get('posts_by_hour', {}).get('09:00', 0)}<br/><br/>
        
        <b>Top Content Categories:</b><br/>
        • Marketing & Brand Content<br/>
        • Professional Updates<br/>
        • Social Commentary<br/>
        • Industry News<br/>
        """
        
        behavior_para = Paragraph(behavior_text, self.styles['Normal'])
        self.story.append(behavior_para)
        self.story.append(Spacer(1, 0.3*inch))
    
    def generate(self):
        """Generate the complete PDF report"""
        # Build report sections in logical order
        self._add_header()
        self._add_executive_summary()
        self._add_profile_overview()
        self._add_methodology()
        self._add_overview_section()
        self._add_risk_assessment_section()
        self._add_compliance_analysis_section()
        self._add_detailed_content_analysis()
        self._add_content_theme_distribution()
        self._add_user_behavior_section()
        self._add_content_quality_section()
        self._add_demographics_section()
        self._add_cultural_analysis_section()
        self._add_key_findings()
        self._add_recommendations_section()
        self._add_footer()
        
        # Build PDF
        self.doc.build(self.story)
        
        # Get PDF bytes
        pdf_bytes = self.buffer.getvalue()
        self.buffer.close()
        
        return pdf_bytes


def generate_admin_pdf_report(report_data: dict) -> bytes:
    """
    Main function to generate admin PDF report
    
    Args:
        report_data: Dictionary containing all report data
        
    Returns:
        bytes: PDF file content
    """
    generator = ContentryPDFReport(report_data)
    return generator.generate()
